kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: sandbox
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry]
      config_path = "/etc/containerd/certs.d"
nodes:
  - role: control-plane
    image: kindest/node:v1.29.2@sha256:51a1434a5397193442f0be2a297b488b6c919ce8a3931be0ce822606ea5ca245
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
#            system-reserved: memory=4Gi,cpu=1
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        listenAddress: "0.0.0.0"
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        listenAddress: "0.0.0.0"
        protocol: TCP
  - role: worker
    image: kindest/node:v1.29.2@sha256:51a1434a5397193442f0be2a297b488b6c919ce8a3931be0ce822606ea5ca245
  #   kubeadmConfigPatches:
  #   - |
  #       kind: JoinConfiguration
  #       nodeRegistration:
  #         kubeletExtraArgs:
  #           system-reserved: memory=4Gi,cpu=1
  - role: worker
    image: kindest/node:v1.29.2@sha256:51a1434a5397193442f0be2a297b488b6c919ce8a3931be0ce822606ea5ca245
  #   kubeadmConfigPatches:
  #     - |
  #       kind: JoinConfiguration
  #       nodeRegistration:
  #         kubeletExtraArgs:
  #           system-reserved: memory=4Gi,cpu=1
  - role: worker
    image: kindest/node:v1.29.2@sha256:51a1434a5397193442f0be2a297b488b6c919ce8a3931be0ce822606ea5ca245
  #   kubeadmConfigPatches:
  #     - |
  #       kind: JoinConfiguration
  #       nodeRegistration:
  #         kubeletExtraArgs:
  #           system-reserved: memory=4Gi,cpu=1
