FROM quay.io/strimzi/kafka:0.40.0-kafka-3.7.0

USER root:root
RUN mkdir -p /opt/kafka/plugins/debezium-postgres-connector/postgres254 \
    && curl -f -L --output /opt/kafka/plugins/debezium-postgres-connector/postgres254.tgz https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/2.5.4.Final/debezium-connector-postgres-2.5.4.Final-plugin.tar.gz \
    && tar xvfz /opt/kafka/plugins/debezium-postgres-connector/postgres254.tgz -C /opt/kafka/plugins/debezium-postgres-connector/postgres254 \
    && rm -vf /opt/kafka/plugins/debezium-postgres-connector/postgres254.tgz
USER 1001

